(source gnu)
(source melpa)
(source marmalade)
(source org)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "dash")
(depends-on "findr")
(depends-on "floobits")
(depends-on "flx-ido")
(depends-on "highlight")
(depends-on "highlight-indentation")
(depends-on "hlinum")
(depends-on "inf-ruby")
(depends-on "magit")
(depends-on "magithub")
(depends-on "multi-term")
(depends-on "multiple-cursors")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "recentf-ext")
(depends-on "rubocop")
(depends-on "ruby-compilation")
(depends-on "ruby-tools")
(depends-on "color-theme-solarized")
;; evil-mode members
(depends-on "evil")
(depends-on "evil-args")
(depends-on "evil-surround")
(depends-on "evil-numbers")
(depends-on "evil-terminal-cursor-changer")
(depends-on "evil-nerd-commenter")

;; syntax
(depends-on "markdown-mode")
(depends-on "livescript-mode")
(depends-on "clojure-mode")

